config/routes.rb
Rails.application.routes.draw do

  get 'users/index'

  devise_for :users

  resources :lakes do
    resources :marine_animals
  end
  resources :marine_animals

  resources :users, only: [:index]

  root 'welcome#index'

end

app/models/lake.rb
class Lake < ActiveRecord::Base
  validates :name, presence: true, length: {minimum: 2, maximum: 20}
  validates :size, presence:true, numericality: {only_integer: true}
  validates :fish_density, presence: true, inclusion: {in:['low','medium', 'high']}

  has_many :marine_animals
  belongs_to :user
end

app/models/marine_animal.rb
class MarineAnimal < ActiveRecord::Base
  validates :species, presence: true, length: {maximum: 40}
  validates :weight, presence: true, numericality: {greater_than: 0}
  validates :age, presence: true, numericality: {only_integer: true, greater_than: 0}

  belongs_to :lake
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lakes
  has_many :marine_animals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    def require_login
       unless current_user
         redirect_to new_user_session_path
    end
  end

end

app/controllers/lakes_controller.rb
class LakesController < ApplicationController

  before_filter :require_login, :only =>[:create, :update, :destroy, :edit, :new]
  before_action :get_lake, :only => [:show, :edit, :update, :destroy, :check_user_owns]
  before_action :check_user_owns, only: [:edit, :update, :destroy]

  def get_lake
    @lake = Lake.find(params[:id])
  end

  def check_user_owns
    if @lake.user != current_user
      flash[:notice] = "Unable to edit, you don't own this lake!"
      redirect_to request.referer
    end
  end

  def new
    @lake = Lake.new
  end

  def index

  end

  def show
      fish_in_lake = @lake.marine_animals.pluck(:species)
      @fishes_info = fish_in_lake.each_with_object(Hash.new(0)) { |e, h| h[e] += 1}
  end

  def edit
  end

  def create
      @lake = Lake.new(lake_params)
      @lake.user_id = current_user.id

      if @lake.save
        redirect_to @lake
      else
        render 'new'
      end
  end

  def update
      if @lake.update(lake_params)
        redirect_to @lake
      else
        render 'edit'
      end
  end

  def destroy
      @lake.destroy
      redirect_to lakes_path
  end

  private
    def lake_params
        params.require(:lake).permit(:name,:size,:fish_density);
    end

end

app/controllers/marine_animals_controller.rb
class MarineAnimalsController < ApplicationController

  before_filter :require_login, :only =>[:create, :update, :destroy, :edit, :new]
  before_action :get_marine_animal, only: [:edit, :show, :update, :destroy, :check_user_owns]
  before_action :check_user_owns, only: [:edit, :update, :destroy]

  def get_marine_animal
    @marine_animal = MarineAnimal.find(params[:id])
  end

  def check_user_owns
    if @marine_animal.user != current_user
      flash[:notice] = "You cannot edit this marine animal as you don't own it"
      redirect_to request.referer
    end
  end

  def index
    if params.has_key?(:species)
      @species = params[:species]
      @marine_animals_to_list = MarineAnimal.where(:species => params[:species])
    else
      @marine_animals_to_list = MarineAnimal.all
    end

    #if there is a lake_id, then there is no need to display the lake column in the iew

   if params.has_key?(:lake_id)
      @lake = Lake.find(params[:lake_id]).name
   end
  end

  def new
      @marine_animal = MarineAnimal.new
  end

  def edit
  end

  def show
  end

  def update
     if @marine_animal.update(marine_animals_params)
       redirect_to @marine_animal
     else
       render 'edit'
     end
  end

  def create
    if params.has_key?(:lake_id)
      @lake = Lake.find(params[:lake_id])
      @marine_animal = MarineAnimal.new(marine_animals_params)
      @marine_animal.user_id = current_user.id

      if @marine_animal.save
        @lake.marine_animals.push(@marine_animal)
        redirect_to lake_path(@lake)
      else
        flash[:errors] = @marine_animal.errors.full_messages
        redirect_to lake_path(@lake)
      end
    else
      @marine_animal = MarineAnimal.new(marine_animals_params)
      @marine_animal.user_id = current_user.id
      if @marine_animal.save
        redirect_to @marine_animal
      else
        render 'new'
      end
    end
  end

  def destroy
      @marine_animal.destroy
      redirect_to marine_animals_path
  end

  private
    def marine_animals_params
      params.require(:marine_animal).permit(:age,:weight,:species,:lake_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :require_login

  def index
    @users = User.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fish_helper.rb
module FishHelper
end

app/helpers/lakes_helper.rb
module LakesHelper
end

app/helpers/marine_animals_helper.rb
module MarineAnimalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/lakes/_form.html.erb
<%= simple_form_for @lake do |l| %>
    <%= l.input :name , label: 'Lake name', input_html: {maxlength:20} %>
    <%= l.input :size, label: 'Lake size'%>
    <%= l.input :fish_density, collection: ["low", "medium", "high"] , as: :select %>
    <%= l.button :submit %>

    <% if @lake.errors.any? %>
        <div class = "hint">
          <ul>
            <% @lake.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
<% end %>

app/views/lakes/edit.html.erb
<h1>Edit a lake</h1>

<%= render 'form' %>

<%= link_to "back", lakes_path %>

app/views/lakes/fishinlake.html.erb
<h1>List of <%= @species %> in <%= @lake.name %></h1>

    <table>
      <tr>
        <th>id</th>
        <th>weight</th>
        <th>Age</th>
      </tr>
      <% @fishes_info.each do |f| %>
          <tr>
            <td><%= f.id %></td>
            <td><%= f.weight %></td>
            <td><%= f.age %></td>
          </tr>
      <% end %>
    </table>

app/views/lakes/index.html.erb
<h1>List of all lakes:</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Size</th>
    <th>Density</th>
    <th>Owner</th>
  </tr>

  <% Lake.all.each do |l|%>
      <tr>
        <td><%= link_to l.name, lake_path(l) %></td>
        <td><%= l.size %></td>
        <td><%= l.fish_density %></td>
        <td><%= l.user.email %></td>
        <td><%= link_to "edit", edit_lake_path(l) %></td>
        <td><%= link_to "delete", lake_path(l), method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<%= link_to "back", root_path %>

app/views/lakes/new.html.erb
<h1>New Lake</h1>

<%= render 'form' %>

<%= link_to "back", root_path %>

app/views/lakes/show.html.erb
<h1>Lake information</h1>

<p>
  <strong>Name:</strong>
  <%= @lake.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @lake.size %>
</p>

<p>
  <strong>Density:</strong>
  <%= @lake.fish_density %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @lake.user.email %>
</p>

<h2>Fishes:</h2>
    <% if @lake.marine_animals.size == 0 %>
        <em>No fishes in this lake</em>
    <% else %>
        <table>
          <tr>
            <th>Species</th>
            <th>Count</th>
          </tr>
            <% @fishes_info.each do |f| %>
              <tr>
                <td><%= f[0] %></td>
                <td><%= f[1] %></td>
                <td><%= link_to "more detail", lake_marine_animals_path(@lake[:id], species: f[0]) %></td>
              </tr>
            <% end %>
        </table>
    <% end %>

<h2>Add fish to lake:</h2>
<%= simple_form_for([@lake, @lake.marine_animals.build]) do |f| %>
    <%= f.input :species , label: 'Species', input_html: {maxlength:20} %>
    <%= f.input :weight, label: 'Weight(kg)'%>
    <%= f.input :age, label: 'Age' %>
    <%= f.button :submit %>

    <% if flash[:errors] && !flash[:errors].empty? %>
        <div class = "hint">
          <%= flash[:errors].inspect %>
        </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FisherySim</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- this code is crappy! -->
<div id ="errorContainer" style="display: <% if flash[:notice] %><%= 'block;' %><% else %><%= 'none;' %><% end %>">
  <% flash.each do |k, v| %>
      <div id="<%= k %>"><%= v %></div>
  <% end %>
</div>
<div id="container">

  <div id="user_nav">
    <% if user_signed_in? %>
       Signed in as <%= current_user.email %>. Not you?
       <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% else %>
       <%= link_to "Sign up" , new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>.
    <% end %>
  </div>

  <%= yield %>
</div>

</body>
</html>

app/views/marine_animals/_form.html.erb
<%= simple_form_for @marine_animal do |l| %>
    <%= l.input :species , label: 'Species', input_html: {maxlength:20} %>
    <%= l.input :weight, label: 'Weight(kg)'%>
    <%= l.input :age, label: 'Age' , hint: 'hint: blah blah' %>

    <% if controller.action_name == 'new' || controller.action_name == 'edit' %>
        <%=
        #l.input :lake_id, label: 'Lake', collection: Lake.all, as: :select
        l.association :lake
        %>
    <% end %>

    <%= l.button :submit %>

    <% if @marine_animal.errors.any? %>
        <div class = "hint">
          <ul>
            <% @marine_animal.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

<% end %>

app/views/marine_animals/edit.html.erb
<h1>Edit Fish</h1>

<% flash.each do |k, v| %>
    <div id="<%= k %>"><%= v %></div>
<% end %>

<%= render 'form' %>

app/views/marine_animals/index.html.erb
<h1>Marine animals page</h1>

<% if @lake %>
    <h2>Lake: <%= @lake %></h2>
<% end %>
<% if @species %>
    <h2>Species: <%= @species %></h2>
<% end %>

<table>
  <tr>
    <th>id</th>
    <th>Species</th>
    <th>Weight(kg)</th>
    <th>Age</th>
    <% if params.has_key?(:lake_id) == false  %>
        <th>Lake</th>
    <% end %>
    <th>Owner</th>
  </tr>

  <%= puts @marine_animals_to_list.inspect %>

  <% @marine_animals_to_list.each do |f|%>
      <tr>
        <td><%= f.id %></td>
        <td><%= f.species %></td>
        <td><%= f.weight %></td>
        <td><%= f.age %></td>
        <% if params.has_key?(:lake_id) == false%>

            <% if f.has_attribute?(:lake_id) && f.lake %>
                <td><%= f.lake.name %></td>
            <% else %>
               <td>"N/A"</td>
            <% end %>

        <% end %>
        <td><%= f.user.email %></td>
        <td><%= link_to "edit", edit_marine_animal_path(f) %></td>
        <td><%= link_to "delete", marine_animal_path(f), method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<%= link_to "home", root_path %>
<br>
<% if params.has_key?(:lake_id)%>
    <%= link_to "Back to lake", lake_path(params[:lake_id]) %>
<% end %>

app/views/marine_animals/new.html.erb
<h1>Create marine animal</h1>

<% flash.each do |k, v| %>
    <div id="<%= k %>"><%= v %></div>
<% end %>

<%= render 'form' %>

app/views/marine_animals/show.html.erb
<h1>Fish information</h1>

<p>
  <strong>Species:</strong>
  <%= @marine_animal.species %>
</p>

<p>
  <strong>Weight(kg):</strong>
  <%= @marine_animal.weight %>
</p>

<p>
  <strong>Age:</strong>
  <%= @marine_animal.age %>
</p>

<p>
  <strong>Lake:</strong>
  <% if @marine_animal.lake %>
    <%= @marine_animal.lake.name %>
  <% else %>
    Not in a lake.
  <% end %>
</p>

app/views/users/index.html.erb
<h1>User list:</h1>
<ul>
  <% @users.each do |user| %>
      <li><%= user.email %></li>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<h1>Fishery Sim</h1>

<h2>Pages</h2>
Show all lakes:
<%= link_to 'Browse all lakes', lakes_path %>
<br>
Create new lake: <%= link_to 'Create new lake', new_lake_path %>

<br><br>
Show all marine animals: <%= link_to "Browse all marine animals", marine_animals_path %>
<br>
Create new marine animal: <%= link_to "Create new marine animal", new_marine_animal_path %>
<br><br>
Display email of all users: <%= link_to "List all users", users_path %>


<h2>Info</h2>

<strong>Lakes</strong> have a size and density. A lake can hold many marine animals. <br>

A <strong>Marine animal(fish)</strong> has a weight and age. A fish may belong to a lake, but it doesn't have to.